SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `excord`.`ec_history` CHANGE COLUMN `change_ip` `change_ip` VARCHAR(45) NULL DEFAULT NULL  ;

ALTER TABLE `excord`.`ec_requirement` CHANGE COLUMN `name` `name` VARCHAR(45) NULL DEFAULT NULL  , CHANGE COLUMN `release_name` `release_name` VARCHAR(45) NULL DEFAULT NULL  , CHANGE COLUMN `product` `product` VARCHAR(45) NULL DEFAULT NULL  ;

ALTER TABLE `excord`.`ec_testfolder` CHANGE COLUMN `name` `name` VARCHAR(45) NOT NULL  ;

ALTER TABLE `excord`.`ec_testplan` CHANGE COLUMN `name` `name` VARCHAR(45) NOT NULL ;

ALTER TABLE `excord`.`ec_testresult` CHANGE COLUMN `environment` `environment` VARCHAR(45) NULL DEFAULT NULL  ;

ALTER TABLE `excord`.`ec_testupload` CHANGE COLUMN `caption` `caption` VARCHAR(45) NULL DEFAULT NULL  ;

ALTER TABLE `excord`.`ec_user` CHANGE COLUMN `name` `name` VARCHAR(45) NULL DEFAULT NULL  , CHANGE COLUMN `email` `email` VARCHAR(45) NULL DEFAULT NULL ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
